[package]
name = "invaders-architecture"
version = "0.1.0"
authors = ["Leah Ferrell <leahferrell03@gmail.com>"]
edition = "2018"

[lib]
name = "architecture"
path = "src/lib.rs"

[dependencies]
strum = "0.15.0"
strum_macros = "0.15.0"